name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout source
    - name: Checkout
      uses: actions/checkout@v2
    
    # Prepare developer key
    - name: Prepare developer key
      env:
        DEVELOPER_KEY: ${{ secrets.DEVELOPER_KEY }}
      run: echo $DEVELOPER_KEY | base64 -d > key.der
      
    # Build source using Donkeybrains
    - name: Build using Donkeybrains image
      uses: docker://jokarls/donkeybrains:latest
      with:
        args: monkeyc -d edge820 -o bin/app.prg -f monkey.jungle -y key.der

